### ISSUE TITLE
Recover.TSN error

### ISSUE THREAD

**Issue by townsk** [battle-lab/twn_tsn#1]
Hi there, 

I wanted to use your recover TSN method after running BicMix - I am getting this error, which I think has to do with the covariate files not being formatted correctly so that the output of find.fac.spec is empty.

######
Error: $ operator is invalid for atomic vectors
In addition: Warning messages:
1: In matrix(scan(paste(dir, sd, "/LAM_", itr, sep = "")), ncol = nG) :
  data length [366618] is not a sub-multiple or multiple of the number of columns [17463]
2: In matrix(scan(paste(dir, sd, "/LAM_", itr, sep = "")), ncol = nG) :
  data length [349160] is not a sub-multiple or multiple of the number of columns [17463]
#####

Could you provide examples of the input file formats ? 

Many thanks!

**Comment by gewirtz** [comment]
From the warning messages, it seems as though the first issue is reading in the LAM file; that nG (the number of genes) is set incorrectly. You should check to see whether you do have 17,463 genes in your data. You can either manually set nG in the code, or ensure that the gene names input file (Path to file with one ensembl gene label per line, in the same order as in the expression matrix), is coded correctly (no header) and matches to the correct number of genes.

**Comment by gewirtz** [comment]
Have you checked the readme file for input file formats? If you have and you are still confused about something, please ask specifically and I can address it :)

**Comment by townsk** [comment]
Gotcha, I'll check that first. I have the readme, I think the main thing I want to clarify is that I'm understanding this correctly. 
For the expression matrix, I should have all samples across all tissues as columns. The sample size file has the corresponding #of samples that belong to each tissue in order so that if tissue 1 has 10 samples the first 10 columns of the expression matrix are assigned as tissue 1. Is that correct?

**Comment by gewirtz** [comment]
What do you mean by the sample size file? And no, they don't need to be in order --they should match the order in the expression matrix originally fed to bicmix. I believe the covariate matrix is an indicator matrix, so if tissue 1 has 10 samples, then whichever row corresponds to tissue 1 should have a 1 wherever a tissue 1 sample is and 0 elsewhere, separated by tabs.
